name: Go CI

on:
  push:
    branches: [master, develop]
    paths:
      - "**.go"
  pull_request:
    branches: [master, develop]
    paths:
      - "**.go"

jobs:
  go-ci:
    name: Go CI
    runs-on: self-hosted
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Lint Backend
        run: make lint-backend

      - name: Test
        run: go test -v ./...
